package ru.ufalinux.tasp.dataworks;

public enum Types {
	R_OPEN, A_OK, R_ORDER, A_STOPSID, A_ERR, A_INFO, A_DRVSTATEID, R_DRVSTATEID, R_UPDATE, R_TAXSTART, NONE, R_CONFIG, A_CONFIG, A_TARIF,
	R_FREERUN,A_ORDER_CONFIRM, A_ORDER_WAITING,A_ORDER_ONDRIVE, A_ORDER_COMPLETE, R_CLOSE,R_ORDERID,R_ANDROIDUPDATE, R_OVERSPEED, A_ORDER_PAUSED
}
